baseURL = "https://lokal.ninja/hessen"
languageCode = "de-DE"
title = "Lokal Ninja - Hessen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Hessen"
  repo = "hessen"
